/*
|--------------------------------------------------------------------------
| Commands loader
|--------------------------------------------------------------------------
|
| Ace loads a package's commands through the module a host names in the
| `commands` array of its adonisrc (`configure` adds this one):
| `getMetaData()` lists the commands and `getCommand()` imports the one being
| run. The metadata comes from `commands.json`, generated by
| `npm run index:commands`, so listing commands imports none of them.
|
*/

import { readFile } from 'node:fs/promises'
import type { BaseCommand } from '@adonisjs/core/ace'
import type { CommandMetaData } from '@adonisjs/core/types/ace'

type IndexedCommand = CommandMetaData & { filePath: string }

let commands: IndexedCommand[] | undefined

export async function getMetaData(): Promise<IndexedCommand[]> {
  if (!commands) {
    const index = await readFile(new URL('./commands.json', import.meta.url), 'utf8')
    commands = JSON.parse(index).commands as IndexedCommand[]
  }
  return commands
}

export async function getCommand(metaData: CommandMetaData): Promise<typeof BaseCommand | null> {
  const indexed = await getMetaData()
  const command = indexed.find(({ commandName }) => commandName === metaData.commandName)
  if (!command) {
    return null
  }

  const { default: commandConstructor } = await import(
    new URL(command.filePath, import.meta.url).href
  )
  return commandConstructor
}
